In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [33]:
candy = pd.read_csv('candy-data.csv')
candy.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  
0   66.971725  
1   67.602936  
2   32.261086  
3   46.116505  
4   52.341465

In [34]:
candy['competitorname'].unique()

array(['100 Grand', '3 Musketeers', 'One dime', 'One quarter',
       'Air Heads', 'Almond Joy', 'Baby Ruth', 'Boston Baked Beans',
       'Candy Corn', 'Caramel Apple Pops', 'Charleston Chew',
       'Chewey Lemonhead Fruit Mix', 'Chiclets', 'Dots', 'Dum Dums',
       'Fruit Chews', 'Fun Dip', 'Gobstopper', 'Haribo Gold Bears',
       'Haribo Happy Cola', 'Haribo Sour Bears', 'Haribo Twin Snakes',
       'HersheyÕs Kisses', 'HersheyÕs Krackel',
       'HersheyÕs Milk Chocolate', 'HersheyÕs Special Dark', 'Jawbusters',
       'Junior Mints', 'Kit Kat', 'Laffy Taffy', 'Lemonhead',
       'Lifesavers big ring gummies', 'Peanut butter M&MÕs', 'M&MÕs',
       'Mike & Ike', 'Milk Duds', 'Milky Way', 'Milky Way Midnight',
       'Milky Way Simply Caramel', 'Mounds', 'Mr Good Bar', 'Nerds',
       'Nestle Butterfinger', 'Nestle Crunch', 'Nik L Nip', 'Now & Later',
       'Payday', 'Peanut M&Ms', 'Pixie Sticks', 'Pop Rocks', 'Red vines',
       'ReeseÕs Miniatures', 'ReeseÕs Peanut Butter cup'

In [35]:
candy['chocolate'].unique()

array([1, 0], dtype=int64)

In [36]:
candy['sugarpercent'].unique()

array([0.73199999, 0.60399997, 0.011     , 0.90600002, 0.465     ,
       0.31299999, 0.046     , 0.127     , 0.43000001, 0.093     ,
       0.197     , 0.22      , 0.26699999, 0.82499999, 0.87199998,
       0.30199999, 0.96499997, 0.84799999, 0.59299999, 0.58099997,
       0.034     , 0.72000003, 0.40599999, 0.98799998, 0.86000001,
       0.94099998, 0.546     , 0.069     , 0.15099999, 0.56900001,
       0.41800001, 0.162     , 0.17399999, 0.186     ])

In [37]:
candy['winpercent'].unique()

array([66.971725, 67.602936, 32.261086, 46.116505, 52.341465, 50.347546,
       56.914547, 23.417824, 38.010963, 34.517681, 38.975037, 36.017628,
       24.524988, 42.272076, 39.460556, 43.088924, 39.185505, 46.783348,
       57.11974 , 34.158958, 51.41243 , 42.178772, 55.375454, 62.284481,
       56.490501, 59.236122, 28.127439, 57.21925 , 76.7686  , 41.389557,
       39.141056, 52.911392, 71.46505 , 66.574585, 46.411716, 55.064072,
       73.099556, 60.800701, 64.35334 , 47.829754, 54.526451, 55.354046,
       70.735641, 66.47068 , 22.445341, 39.4468  , 46.296597, 69.483788,
       37.722336, 41.265511, 37.348522, 81.866257, 84.18029 , 73.43499 ,
       72.887901, 35.290756, 65.716286, 29.703691, 42.849144, 34.722   ,
       63.08514 , 55.103695, 37.887188, 45.995827, 76.673782, 59.529251,
       59.863998, 52.825947, 67.037628, 34.578991, 33.43755 , 32.230995,
       27.303865, 54.861111, 48.982651, 43.068897, 45.736748, 49.653503,
       47.173229, 81.642914, 45.466282, 39.011898, 

In [38]:
candy['fruity'].unique()

array([0, 1], dtype=int64)

In [39]:
candy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   competitorname    85 non-null     object 
 1   chocolate         85 non-null     int64  
 2   fruity            85 non-null     int64  
 3   caramel           85 non-null     int64  
 4   peanutyalmondy    85 non-null     int64  
 5   nougat            85 non-null     int64  
 6   crispedricewafer  85 non-null     int64  
 7   hard              85 non-null     int64  
 8   bar               85 non-null     int64  
 9   pluribus          85 non-null     int64  
 10  sugarpercent      85 non-null     float64
 11  pricepercent      85 non-null     float64
 12  winpercent        85 non-null     float64
dtypes: float64(3), int64(9), object(1)
memory usage: 8.8+ KB


In [40]:
candy['sugarpercent'].unique()

array([0.73199999, 0.60399997, 0.011     , 0.90600002, 0.465     ,
       0.31299999, 0.046     , 0.127     , 0.43000001, 0.093     ,
       0.197     , 0.22      , 0.26699999, 0.82499999, 0.87199998,
       0.30199999, 0.96499997, 0.84799999, 0.59299999, 0.58099997,
       0.034     , 0.72000003, 0.40599999, 0.98799998, 0.86000001,
       0.94099998, 0.546     , 0.069     , 0.15099999, 0.56900001,
       0.41800001, 0.162     , 0.17399999, 0.186     ])

#Quality of Data 
1. Win rate to 3 decimal places.
2. Sugarpercent to 3 decimal places.
3. Competitor name choose the first 3 string in the name

In [57]:
candy['winpercent']=candy['winpercent'].round(3)

In [56]:
candy['sugarpercent']=candy['sugarpercent'].round(3)

In [55]:
candy['competitorname']=candy['competitorname'].astype(str).str.split(' ').str.slice(0,3).str.join(' ')

In [52]:
candy['winpercent'].round(3)
candy

competitorname  chocolate  fruity  caramel  peanutyalmondy  \
0                    100 Grand          1       0        1               0   
1                 3 Musketeers          1       0        0               0   
2                     One dime          0       0        0               0   
3                  One quarter          0       0        0               0   
4                    Air Heads          0       1        0               0   
..                         ...        ...     ...      ...             ...   
80                   Twizzlers          0       1        0               0   
81                    Warheads          0       1        0               0   
82        WelchÕs Fruit Snacks          0       1        0               0   
83  WertherÕs Original Caramel          0       0        1               0   
84                    Whoppers          1       0        0               0   

    nougat  crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0        0                 1     0    1         0         0.732         0.860   
1        1                 0     0    1         0         0.604         0.511   
2        0                 0     0    0         0         0.011         0.116   
3        0                 0     0    0         0         0.011         0.511   
4        0                 0     0    0         0         0.906         0.511   
..     ...               ...   ...  ...       ...           ...           ...   
80       0                 0     0    0         0         0.220         0.116   
81       0                 0     1    0         0         0.093         0.116   
82       0                 0     0    0         1         0.313         0.313   
83       0                 0     1    0         0         0.186         0.267   
84       0                 1     0    0         1         0.872         0.848   

    winpercent  
0    66.971725  
1    67.602936  
2    32.261086  
3    46.116505  
4    52.341465  
..         ...  
80   45.466282  
81   39.011898  
82   44.375519  
83   41.904308  
84   49.524113  

[85 rows x 13 columns]

#Model building this section will be used to build the logistic regression model
Y axis will be the winpercent 
X axis will be the remaining columns